name: Workflow for Deploy Blog Client
on:
  push:
    branches:
      - master
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: CI=false npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-southeast-1

      # - name: Deploy to S3 bucket
      #   run: aws s3 sync ./build/ s3://thieuanhnguyen.com --delete
      - name: Deploy to EC2 instance
        env:
          SSH_KEY: ${{ secrets.SSH_KEY  }}
          HOSTNAME : ${{ secrets.HOSTNAME  }}
          USERNAME : ${{ secrets.USERNAME  }}
        run: |
          echo "$SSH_KEY" > ssh_key && chmod 600 ssh_key
          rsync -Pav -e "ssh -i ./ssh_key" ./build/ ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:/projects/blogger_client