name: Workflow for Deploy Blog Client
on:
  pull:
    branches:
      - master
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: CI=false npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - name: Deploy to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "./build"
          target: "/home/ubuntu/projects/blogger_client"